/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestaooficina.view;

import com.mycompany.gestaooficina.control.GerenciamentoClientes;
import com.mycompany.gestaooficina.control.GerenciamentoFuncionarios;
import com.mycompany.gestaooficina.control.GerenciamentoOrdemServico;
import com.mycompany.gestaooficina.control.GerenciamentoPecas;
import com.mycompany.gestaooficina.control.GerenciamentoServicos;
import com.mycompany.gestaooficina.control.GerenciamentoVeiculos;
import javax.swing.JOptionPane;

/**
 *
 * @author silvestre
 */
public class Buscar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Buscar.class.getName());

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
        this.setSize(600, 350);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonVerFuncionario = new javax.swing.JButton();
        jButtonVerClientes = new javax.swing.JButton();
        jButtonVerVeiculo = new javax.swing.JButton();
        jButtonVerPeca = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButtonVerServico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jButtonVerFuncionario.setBackground(new java.awt.Color(0, 51, 153));
        jButtonVerFuncionario.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonVerFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerFuncionario.setText("Buscar Funcionario");
        jButtonVerFuncionario.addActionListener(this::jButtonVerFuncionarioActionPerformed);

        jButtonVerClientes.setBackground(new java.awt.Color(0, 51, 153));
        jButtonVerClientes.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonVerClientes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerClientes.setText("Buscar Clientes");
        jButtonVerClientes.addActionListener(this::jButtonVerClientesActionPerformed);

        jButtonVerVeiculo.setBackground(new java.awt.Color(0, 51, 153));
        jButtonVerVeiculo.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonVerVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerVeiculo.setText("Buscar Veiculos");
        jButtonVerVeiculo.addActionListener(this::jButtonVerVeiculoActionPerformed);

        jButtonVerPeca.setBackground(new java.awt.Color(0, 51, 153));
        jButtonVerPeca.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonVerPeca.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerPeca.setText("Buscar Peça");
        jButtonVerPeca.addActionListener(this::jButtonVerPecaActionPerformed);

        jButton5.setBackground(new java.awt.Color(0, 51, 153));
        jButton5.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Buscar Ordem de Serviço");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButtonVerServico.setBackground(new java.awt.Color(0, 51, 153));
        jButtonVerServico.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonVerServico.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerServico.setText("Buscar Serviço");
        jButtonVerServico.addActionListener(this::jButtonVerServicoActionPerformed);

        jLabel1.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar");

        jButtonVoltar.setBackground(new java.awt.Color(255, 0, 0));
        jButtonVoltar.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(this::jButtonVoltarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonVerClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonVerFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonVerPeca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonVerVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel1)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonVoltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonVerServico, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVoltar)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonVerVeiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonVerPeca))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonVerFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonVerClientes)))
                .addGap(36, 36, 36)
                .addComponent(jButtonVerServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerPecaActionPerformed
        // TODO add your handling code here:
        GerenciamentoPecas genPeca = GerenciamentoPecas.getInstance();
        var cod = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite o codigo que deseja buscar"));
        this.setVisible(false);
        var peca = genPeca.buscarPeca(cod);
        if(peca == null){
            JOptionPane.showMessageDialog(null, "Peca nao encontrada.");
        }else{
            JOptionPane.showMessageDialog(null, peca.visualizarPeca());
        }
        this.setVisible(true);
    }//GEN-LAST:event_jButtonVerPecaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //VER ORDENS DE SERVICO
        GerenciamentoOrdemServico genOS = GerenciamentoOrdemServico.getInstance();
        var cod = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite o codigo que deseja buscar"));
        this.setVisible(false);
        var os = genOS.buscarOrdemServico(cod);
        if(os == null){
            JOptionPane.showMessageDialog(null, "Ordem de serviço nao encontrada.");
        }else{
            JOptionPane.showMessageDialog(null, os.visualizarOrdemServico());
        }
        this.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonVerServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerServicoActionPerformed
        // VER SERVICO
        GerenciamentoServicos genServico = GerenciamentoServicos.getInstance();
        var cod = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite o codigo que deseja buscar"));
        this.setVisible(false);
        var os = genServico.buscarServico(cod);
        if(os == null){
            JOptionPane.showMessageDialog(null, "Serviço nao encontrado.");
        }else{
            JOptionPane.showMessageDialog(null, os.visualizarServico());
        }
        this.setVisible(true);
    }//GEN-LAST:event_jButtonVerServicoActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // HOME
        Home home = new Home();
        this.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonVerClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerClientesActionPerformed
        // VER CLIENTE
        GerenciamentoClientes genClient = GerenciamentoClientes.getInstance();
        var cod = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite o codigo que deseja buscar"));
        this.setVisible(false);
        var os = genClient.buscarCliente(cod);
        if(os == null){
            JOptionPane.showMessageDialog(null, "Cliente nao encontrado.");
        }else{
            JOptionPane.showMessageDialog(null, os.visualizarCliente());
        }
        this.setVisible(true);
    }//GEN-LAST:event_jButtonVerClientesActionPerformed

    private void jButtonVerFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerFuncionarioActionPerformed
        // VER FUNCIONARIO
        GerenciamentoFuncionarios genFunc = GerenciamentoFuncionarios.getInstance();
        var cod = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite o codigo que deseja buscar"));
        this.setVisible(false);
        var os = genFunc.buscarFuncionario(cod);
        if(os == null){
            JOptionPane.showMessageDialog(null, "Funcionario nao encontrada.");
        }else{
            JOptionPane.showMessageDialog(null, os.visualizarFuncionario());
        }
        this.setVisible(true);
    }//GEN-LAST:event_jButtonVerFuncionarioActionPerformed

    private void jButtonVerVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerVeiculoActionPerformed
        // VER VEICULO
        GerenciamentoVeiculos genVeic = GerenciamentoVeiculos.getInstance();
        var cod = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite o codigo que deseja buscar"));
        this.setVisible(false);
        var os = genVeic.buscarVeiculo(cod);
        if(os == null){
            JOptionPane.showMessageDialog(null, "Ordem de serviço nao encontrada.");
        }else{
            JOptionPane.showMessageDialog(null, os.visualizarVeiculo());
        }
        this.setVisible(true);
    }//GEN-LAST:event_jButtonVerVeiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Buscar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonVerClientes;
    private javax.swing.JButton jButtonVerFuncionario;
    private javax.swing.JButton jButtonVerPeca;
    private javax.swing.JButton jButtonVerServico;
    private javax.swing.JButton jButtonVerVeiculo;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
