/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestaooficina.view;

/**
 *
 * @author silvestre
 */
public class Cadastrar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cadastrar.class.getName());

    /**
     * Creates new form Cadastrar
     */
    public Cadastrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadVeic = new javax.swing.JButton();
        jButtonCadPeca = new javax.swing.JButton();
        jButtonCadServ = new javax.swing.JButton();
        jButtonCadOS = new javax.swing.JButton();
        jButtonCadCliente = new javax.swing.JButton();
        jButtonCadFunc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCadVeic.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonCadVeic.setText("Cadastrar Veiculo");
        jButtonCadVeic.addActionListener(this::jButtonCadVeicActionPerformed);

        jButtonCadPeca.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonCadPeca.setText("Cadastrar Peça");
        jButtonCadPeca.addActionListener(this::jButtonCadPecaActionPerformed);

        jButtonCadServ.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonCadServ.setText("Cadastrar Serviço");
        jButtonCadServ.addActionListener(this::jButtonCadServActionPerformed);

        jButtonCadOS.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonCadOS.setText("Cadastrar Ordem de Serviço");
        jButtonCadOS.addActionListener(this::jButtonCadOSActionPerformed);

        jButtonCadCliente.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonCadCliente.setText("Cadastrar Cliente");
        jButtonCadCliente.addActionListener(this::jButtonCadClienteActionPerformed);

        jButtonCadFunc.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonCadFunc.setText("Cadastrar Funcionario");
        jButtonCadFunc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonCadFuncFocusGained(evt);
            }
        });
        jButtonCadFunc.addActionListener(this::jButtonCadFuncActionPerformed);

        jLabel1.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel1.setText("Cadastrar");

        jButtonSair.setBackground(new java.awt.Color(255, 0, 0));
        jButtonSair.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonSair.setText("Voltar");
        jButtonSair.addActionListener(this::jButtonSairActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSair)
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonCadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCadVeic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCadPeca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCadServ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCadOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCadFunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCadCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCadVeic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCadPeca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCadServ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCadOS)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadVeicActionPerformed
        // TODO add your handling code here:
        CadastrarVeiculo cadVei = new CadastrarVeiculo();
        cadVei.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCadVeicActionPerformed

    private void jButtonCadPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadPecaActionPerformed
        // TODO add your handling code here:
        CadastrarPeca cadPeca = new CadastrarPeca();
        cadPeca.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCadPecaActionPerformed

    private void jButtonCadServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadServActionPerformed
        // TODO add your handling code here:
        CadastrarServico cadServ = new CadastrarServico();
        cadServ.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCadServActionPerformed

    private void jButtonCadOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadOSActionPerformed
        // TODO add your handling code here:
        CadastrarOrdemServico cadOS = new CadastrarOrdemServico();
        cadOS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCadOSActionPerformed

    private void jButtonCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadClienteActionPerformed
        // TODO add your handling code here:
        CadastrarCliente cadCli = new CadastrarCliente();
        cadCli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCadClienteActionPerformed

    private void jButtonCadFuncFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonCadFuncFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadFuncFocusGained

    private void jButtonCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadFuncActionPerformed
        // TODO add your handling code here:
        CadastrarFucionario cadFunc = new CadastrarFucionario();
        cadFunc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCadFuncActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        this.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_jButtonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cadastrar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadCliente;
    private javax.swing.JButton jButtonCadFunc;
    private javax.swing.JButton jButtonCadOS;
    private javax.swing.JButton jButtonCadPeca;
    private javax.swing.JButton jButtonCadServ;
    private javax.swing.JButton jButtonCadVeic;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
