/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestaooficina.view;

import com.mycompany.gestaooficina.control.GerenciamentoClientes;
import com.mycompany.gestaooficina.control.GerenciamentoPecas;
import com.mycompany.gestaooficina.control.GerenciamentoServicos;
import com.mycompany.gestaooficina.model.Cliente;
import com.mycompany.gestaooficina.model.Peca;
import com.mycompany.gestaooficina.model.Servico;
import javax.swing.JOptionPane;

/**
 *
 * @author silvestre
 */
public class Editar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Editar.class.getName());

    /**
     * Creates new form Editar
     */
    public Editar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEditClient = new javax.swing.JButton();
        jButtonEditFunc = new javax.swing.JButton();
        jButtonEditVeic = new javax.swing.JButton();
        jButtonEditPeca = new javax.swing.JButton();
        jButtonEditServico = new javax.swing.JButton();
        jButtonEditOS = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonEditClient.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonEditClient.setText("Editar Cliente");
        jButtonEditClient.addActionListener(this::jButtonEditClientActionPerformed);

        jButtonEditFunc.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonEditFunc.setText("Editar Funcionario");
        jButtonEditFunc.addActionListener(this::jButtonEditFuncActionPerformed);

        jButtonEditVeic.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonEditVeic.setText("Editar Veiculo");
        jButtonEditVeic.addActionListener(this::jButtonEditVeicActionPerformed);

        jButtonEditPeca.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonEditPeca.setText("Editar Peça");
        jButtonEditPeca.addActionListener(this::jButtonEditPecaActionPerformed);

        jButtonEditServico.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonEditServico.setText("Editar Serviço");
        jButtonEditServico.addActionListener(this::jButtonEditServicoActionPerformed);

        jButtonEditOS.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonEditOS.setText("Editar Ordem de Serviço");
        jButtonEditOS.addActionListener(this::jButtonEditOSActionPerformed);

        jButtonVoltar.setBackground(new java.awt.Color(255, 0, 0));
        jButtonVoltar.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(this::jButtonVoltarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel1.setText("Editar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonVoltar)
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 185, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonEditOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEditServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEditPeca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEditVeic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEditClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEditFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                        .addGap(182, 182, 182))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonVoltar)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addComponent(jButtonEditFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditVeic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditPeca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditOS)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //EDITAR CLIENTE
    private void jButtonEditClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditClientActionPerformed
        // TODO add your handling code here:
        
        //SOLICITA O CODIGO DO CLIENTE PARA SER EDITADO
        this.setVisible(false);
        int busca = Integer.parseInt(JOptionPane.showInputDialog("Digite o codigo do cliente: "));
        
        //PROCURA SE O CLIENTE EXISTE
        GerenciamentoClientes genClient = GerenciamentoClientes.getInstance();
        Cliente cliente = genClient.buscarCliente(busca);
        
        //CASO O CLIENTE NAO EXISTA, INFORMA QUE NÃO FOI ENCONTRADO
        if(cliente == null){
            JOptionPane.showMessageDialog(null, "Cliente nao encontrado!");
            this.setVisible(true);
        }
        
        //CASO EXISTA, MOSTRA O NOME E ABRE A TELA DE EDIÇAO
        else{
            this.setVisible(false);
            JOptionPane.showMessageDialog(null, "Cliente: " + cliente.getNome());
            EditarCliente editClient = new EditarCliente(cliente);
            editClient.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEditClientActionPerformed

    //EDITAR FUNCIONARIO
    private void jButtonEditFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditFuncActionPerformed
        // TODO add your handling code here:
        EditarFuncionario editFunc = new EditarFuncionario();
        editFunc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonEditFuncActionPerformed

    //EDITAR VEICULO
    private void jButtonEditVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditVeicActionPerformed
        // TODO add your handling code here:
        EditarVeiculo editVeic = new EditarVeiculo();
        editVeic.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonEditVeicActionPerformed

    //EDITAR PEÇA EM ESTOQUE
    private void jButtonEditPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPecaActionPerformed
        // TODO add your handling code here:
        
        //SOLICITA O CODIGO DA PEÇA PARA SER EDITADA
        this.setVisible(false);
        int busca = Integer.parseInt(JOptionPane.showInputDialog("Digite o codigo da peça: "));
        
        //PROCURA SE A PEÇA EXISTE
        GerenciamentoPecas genPeca = GerenciamentoPecas.getInstance();
        Peca peca = genPeca.buscarPeca(busca);
        
        //CASO A PEÇA NAO EXISTA, INFORMA QUE NÃO FOI ENCONTRADO
        if(peca == null){
            JOptionPane.showMessageDialog(null, "Peça nao encontrado!");
            this.setVisible(true);
        }
        
        //CASO EXISTA, MOSTRA O NOME E ABRE A TELA DE EDIÇAO
        else{
            this.setVisible(false);
            JOptionPane.showMessageDialog(null, "Peça: " + peca.getNome());
            EditarPeca editPeca = new EditarPeca(peca);
            editPeca.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEditPecaActionPerformed

    //EDITAR INFORMAÇOES DE SERVIÇO
    private void jButtonEditServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditServicoActionPerformed
        // TODO add your handling code here:
        
        //SOLICITA O CODIGO DO SERVIÇO PARA SER EDITADO
        this.setVisible(false);
        int busca = Integer.parseInt(JOptionPane.showInputDialog("Digite o codigo do serviço: "));
        
        //PROCURA SE O SERVIÇO EXISTE
        GerenciamentoServicos genServico = GerenciamentoServicos.getInstance();
        Servico servico = genServico.buscarServico(busca);
        
        //CASO O SERVIÇO NAO EXISTA, INFORMA QUE NÃO FOI ENCONTRADO
        if(servico == null){
            JOptionPane.showMessageDialog(null, "Serviço nao encontrado!");
            this.setVisible(true);
        }
        
        //CASO EXISTA, MOSTRA O NOME E ABRE A TELA DE EDIÇAO
        else{
            this.setVisible(false);
            JOptionPane.showMessageDialog(null, "Serviço: " + servico.getNome());
            EditarServico editServico = new EditarServico(servico);
            editServico.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEditServicoActionPerformed

    //EDITAR ORDEM DE SERVIÇO
    private void jButtonEditOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditOSActionPerformed
        // TODO add your handling code here:
        EditarOrdemServico editOS = new EditarOrdemServico();
        editOS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonEditOSActionPerformed

    //VOLTAR PARA HOME
    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        this.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Editar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditClient;
    private javax.swing.JButton jButtonEditFunc;
    private javax.swing.JButton jButtonEditOS;
    private javax.swing.JButton jButtonEditPeca;
    private javax.swing.JButton jButtonEditServico;
    private javax.swing.JButton jButtonEditVeic;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
