/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestaooficina.view;

import com.mycompany.gestaooficina.control.GerenciamentoClientes;
import com.mycompany.gestaooficina.control.GerenciamentoFuncionarios;
import com.mycompany.gestaooficina.control.GerenciamentoVeiculos;
import com.mycompany.gestaooficina.control.GerenciamentoOrdemServico;
import com.mycompany.gestaooficina.model.Funcionario;
import com.mycompany.gestaooficina.model.Veiculo;
import com.mycompany.gestaooficina.model.OrdemServico;
import com.mycompany.gestaooficina.control.GerenciamentoPecas;
import com.mycompany.gestaooficina.control.GerenciamentoServicos;
import com.mycompany.gestaooficina.model.Cliente;
import com.mycompany.gestaooficina.model.Peca;
import com.mycompany.gestaooficina.model.Servico;
import javax.swing.JOptionPane;

/**
 *
 * @author silvestre
 */
public class Editar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Editar.class.getName());

    /**
     * Creates new form Editar
     */
    public Editar() {
        initComponents();
        this.setSize(600, 350);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonEditFunc = new javax.swing.JButton();
        jButtonEditVeic = new javax.swing.JButton();
        jButtonEditPeca = new javax.swing.JButton();
        jButtonEditServico = new javax.swing.JButton();
        jButtonEditOS = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonEditClient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jButtonEditFunc.setBackground(new java.awt.Color(0, 51, 153));
        jButtonEditFunc.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonEditFunc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditFunc.setText("Editar Funcionario");
        jButtonEditFunc.addActionListener(this::jButtonEditFuncActionPerformed);

        jButtonEditVeic.setBackground(new java.awt.Color(0, 51, 153));
        jButtonEditVeic.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonEditVeic.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditVeic.setText("Editar Veiculo");
        jButtonEditVeic.addActionListener(this::jButtonEditVeicActionPerformed);

        jButtonEditPeca.setBackground(new java.awt.Color(0, 51, 153));
        jButtonEditPeca.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonEditPeca.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditPeca.setText("Editar Peça");
        jButtonEditPeca.addActionListener(this::jButtonEditPecaActionPerformed);

        jButtonEditServico.setBackground(new java.awt.Color(0, 51, 153));
        jButtonEditServico.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonEditServico.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditServico.setText("Editar Serviço");
        jButtonEditServico.addActionListener(this::jButtonEditServicoActionPerformed);

        jButtonEditOS.setBackground(new java.awt.Color(0, 51, 153));
        jButtonEditOS.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonEditOS.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditOS.setText("Editar Ordem de Serviço");
        jButtonEditOS.addActionListener(this::jButtonEditOSActionPerformed);

        jButtonVoltar.setBackground(new java.awt.Color(255, 0, 0));
        jButtonVoltar.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(this::jButtonVoltarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Editar");

        jButtonEditClient.setBackground(new java.awt.Color(0, 51, 153));
        jButtonEditClient.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonEditClient.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditClient.setText("Editar Cliente");
        jButtonEditClient.addActionListener(this::jButtonEditClientActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonEditClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonEditPeca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(245, 245, 245))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonVoltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonEditOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEditServico, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVoltar)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonEditVeic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditPeca))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonEditFunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditClient)))
                .addGap(18, 18, 18)
                .addComponent(jButtonEditServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditOS)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //EDITAR CLIENTE
    private void jButtonEditClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditClientActionPerformed
        // TODO add your handling code here:
        
        //SOLICITA O CODIGO DO CLIENTE PARA SER EDITADO
        String textoBusca = JOptionPane.showInputDialog("Digite o codigo do cliente: ");
        
        //VERIFICA OS DADOS PASSADOS
        if (textoBusca.isEmpty()){
            JOptionPane.showMessageDialog(null, "O codigo deve ser informado");
            return;
        }
        
        int busca = 0;
        try {
            busca = Integer.parseInt(textoBusca);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Codigo invalido!");
            return;
        }
                
        //PROCURA SE O CLIENTE EXISTE
        GerenciamentoClientes genClient = GerenciamentoClientes.getInstance();
        Cliente cliente = genClient.buscarCliente(busca);
        
        //CASO O CLIENTE NAO EXISTA, INFORMA QUE NÃO FOI ENCONTRADO
        if(cliente == null){
            JOptionPane.showMessageDialog(null, "Cliente nao encontrado!");
            this.setVisible(true);
        }
        
        //CASO EXISTA, ABRE A TELA DE EDIÇAO
        else{
            this.setVisible(false);
            EditarCliente editClient = new EditarCliente(cliente);
            editClient.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEditClientActionPerformed

    //EDITAR FUNCIONARIO
    private void jButtonEditFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditFuncActionPerformed
        //SOLICITA O CODIGO DO FUNCIONARIO PARA SER EDITADO
        var textoBusca = JOptionPane.showInputDialog("Digite o codigo do funcionario: ");
        
        //VERIFICA OS DADOS PASSADOS
        if (textoBusca.isEmpty()){
            JOptionPane.showMessageDialog(null, "O codigo deve ser informado");
            return;
        }
        
        int busca = 0;
        try {
            busca = Integer.parseInt(textoBusca);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Codigo invalido!");
            return;
        }
        
        //PROCURA SE O FUNCIONARIO EXISTE
        GerenciamentoFuncionarios genFunc = GerenciamentoFuncionarios.getInstance();
        Funcionario funcionario = genFunc.buscarFuncionario(busca);
        
        //CASO O FUNCIONARIO NAO EXISTA, INFORMA QUE NAO FOI ENCONTRADO
        if (funcionario == null) {
            JOptionPane.showMessageDialog(null, "Funcionario nao encontrado!");
            this.setVisible(true);
        }
        
        //CASO EXISTA, ABRE A TELA DE EDICAO
        else {
            this.setVisible(false);
            EditarFuncionario editFunc = new EditarFuncionario(funcionario);
            editFunc.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEditFuncActionPerformed

    //EDITAR VEICULO
    private void jButtonEditVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditVeicActionPerformed
        //SOLICITA O CODIGO DO VEICULO PARA SER EDITADO
        var textoBusca = JOptionPane.showInputDialog("Digite o codigo do veiculo: ");
        
        //VERIFICA OS DADOS PASSADOS
        if (textoBusca.isEmpty()){
            JOptionPane.showMessageDialog(null, "O codigo deve ser informado");
            return;
        }
        
        int busca = 0;
        try {
            busca = Integer.parseInt(textoBusca);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Codigo invalido!");
            return;
        }
        
        //PROCURA SE O VEICULO EXISTE
        GerenciamentoVeiculos genVeic = GerenciamentoVeiculos.getInstance();
        Veiculo veiculo = genVeic.buscarVeiculo(busca);
        
        //CASO O VEICULO NAO EXISTA, INFORMA QUE NAO FOI ENCONTRADO
        if (veiculo == null) {
            JOptionPane.showMessageDialog(null, "Veiculo nao encontrado!");
            this.setVisible(true);
        }
        
        //CASO EXISTA, ABRE A TELA DE EDICAO
        else {
            this.setVisible(false);
            EditarVeiculo editVeic = new EditarVeiculo(veiculo);
            editVeic.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEditVeicActionPerformed

    //EDITAR PEÇA EM ESTOQUE
    private void jButtonEditPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPecaActionPerformed
        //SOLICITA O CODIGO DA PEÇA PARA SER EDITADA
        var textoBusca = JOptionPane.showInputDialog("Digite o codigo da peça: ");

        //VERIFICA OS DADOS PASSADOS
        if (textoBusca.isEmpty()){
            JOptionPane.showMessageDialog(null, "O codigo deve ser informado");
            return;
        }
        
        int busca = 0;
        try {
            busca = Integer.parseInt(textoBusca);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Codigo invalido!");
            return;
        }        
        
        //PROCURA SE A PEÇA EXISTE
        GerenciamentoPecas genPeca = GerenciamentoPecas.getInstance();
        Peca peca = genPeca.buscarPeca(busca);
        
        //CASO A PEÇA NAO EXISTA, INFORMA QUE NÃO FOI ENCONTRADO
        if(peca == null){
            JOptionPane.showMessageDialog(null, "Peça nao encontrado!");
            this.setVisible(true);
        }
        
        //CASO EXISTA, ABRE A TELA DE EDIÇAO
        else{
            this.setVisible(false);
            EditarPeca editPeca = new EditarPeca(peca);
            editPeca.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEditPecaActionPerformed

    //EDITAR INFORMAÇOES DE SERVIÇO
    private void jButtonEditServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditServicoActionPerformed
        //SOLICITA O CODIGO DO SERVIÇO PARA SER EDITADO
        var textoBusca = JOptionPane.showInputDialog("Digite o codigo do serviço: ");
        
        //VERIFICA OS DADOS PASSADOS
        if (textoBusca.isEmpty()){
            JOptionPane.showMessageDialog(null, "O codigo deve ser informado");
            return;
        }
        
        int busca = 0;
        try {
            busca = Integer.parseInt(textoBusca);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Codigo invalido!");
            return;
        }
        
        //PROCURA SE O SERVIÇO EXISTE
        GerenciamentoServicos genServico = GerenciamentoServicos.getInstance();
        Servico servico = genServico.buscarServico(busca);
        
        //CASO O SERVIÇO NAO EXISTA, INFORMA QUE NÃO FOI ENCONTRADO
        if(servico == null){
            JOptionPane.showMessageDialog(null, "Serviço nao encontrado!");
            this.setVisible(true);
        }
        
        //CASO EXISTA, ABRE A TELA DE EDIÇAO
        else{
            this.setVisible(false);
            EditarServico editServico = new EditarServico(servico);
            editServico.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEditServicoActionPerformed

    //EDITAR ORDEM DE SERVIÇO
    private void jButtonEditOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditOSActionPerformed
        //SOLICITA O CODIGO DA OS PARA SER EDITADA
        var textoBusca = JOptionPane.showInputDialog("Digite o codigo da Ordem de Servico: ");
        
        //VERIFICA OS DADOS PASSADOS
        if (textoBusca.isEmpty()){
            JOptionPane.showMessageDialog(null, "O codigo deve ser informado");
            return;
        }
        
        int busca = 0;
        try {
            busca = Integer.parseInt(textoBusca);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Codigo invalido!");
            return;
        }
        
        //PROCURA SE A OS EXISTE
        GerenciamentoOrdemServico genOS = GerenciamentoOrdemServico.getInstance();
        OrdemServico os = genOS.buscarOrdemServico(busca);
        
        //CASO A OS NAO EXISTA, INFORMA QUE NAO FOI ENCONTRADA
        if (os == null) {
            JOptionPane.showMessageDialog(null, "Ordem de Servico nao encontrada!");
            this.setVisible(true);
        }
        
        //CASO EXISTA, MOSTRA O CODIGO E ABRE A TELA DE EDICAO
        else {
            this.setVisible(false);
            EditarOrdemServico editOS = new EditarOrdemServico(os);
            editOS.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEditOSActionPerformed

    //VOLTAR PARA HOME
    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        this.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Editar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditClient;
    private javax.swing.JButton jButtonEditFunc;
    private javax.swing.JButton jButtonEditOS;
    private javax.swing.JButton jButtonEditPeca;
    private javax.swing.JButton jButtonEditServico;
    private javax.swing.JButton jButtonEditVeic;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
