/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestaooficina.view;

/**
 *
 * @author silvestre
 */
public class Home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jButtonFuncEdit = new javax.swing.JButton();
        jButtonFuncCad = new javax.swing.JButton();
        jButtonFuncVisu = new javax.swing.JButton();
        jButtonFuncRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel1.setText("Gerenciar Mecanica");

        jButtonSair.setBackground(new java.awt.Color(255, 0, 0));
        jButtonSair.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(this::jButtonSairActionPerformed);

        jButtonFuncEdit.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonFuncEdit.setText("Funçoes de Ediçao");
        jButtonFuncEdit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonFuncEditFocusGained(evt);
            }
        });
        jButtonFuncEdit.addActionListener(this::jButtonFuncEditActionPerformed);

        jButtonFuncCad.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonFuncCad.setText("Funçoes de Cadastro");
        jButtonFuncCad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonFuncCadFocusGained(evt);
            }
        });
        jButtonFuncCad.addActionListener(this::jButtonFuncCadActionPerformed);

        jButtonFuncVisu.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonFuncVisu.setText("Funçoes de Visualizaçao");
        jButtonFuncVisu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonFuncVisuFocusGained(evt);
            }
        });
        jButtonFuncVisu.addActionListener(this::jButtonFuncVisuActionPerformed);

        jButtonFuncRemove.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonFuncRemove.setText("Funçoes de Remoçao");
        jButtonFuncRemove.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonFuncRemoveFocusGained(evt);
            }
        });
        jButtonFuncRemove.addActionListener(this::jButtonFuncRemoveActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonFuncRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonFuncCad, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFuncEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFuncVisu, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSair)
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButtonFuncVisu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonFuncCad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonFuncEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFuncRemove)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonFuncEditFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonFuncEditFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFuncEditFocusGained

    private void jButtonFuncEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncEditActionPerformed
        // TODO add your handling code here:
        Editar edit = new Editar();
        edit.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonFuncEditActionPerformed

    private void jButtonFuncCadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonFuncCadFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFuncCadFocusGained

    private void jButtonFuncCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncCadActionPerformed
        // TODO add your handling code here:
        Cadastrar cad = new Cadastrar();
        cad.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonFuncCadActionPerformed

    private void jButtonFuncVisuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonFuncVisuFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFuncVisuFocusGained

    private void jButtonFuncVisuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncVisuActionPerformed
        // TODO add your handling code here:
        Visualizar visu = new Visualizar();
        visu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonFuncVisuActionPerformed

    private void jButtonFuncRemoveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonFuncRemoveFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFuncRemoveFocusGained

    private void jButtonFuncRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncRemoveActionPerformed
        // TODO add your handling code here:
        Remover remove = new Remover();
        remove.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonFuncRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFuncCad;
    private javax.swing.JButton jButtonFuncEdit;
    private javax.swing.JButton jButtonFuncRemove;
    private javax.swing.JButton jButtonFuncVisu;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
