/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestaooficina.view;

import com.mycompany.gestaooficina.control.GerenciamentoClientes;
import com.mycompany.gestaooficina.control.GerenciamentoFuncionarios;
import com.mycompany.gestaooficina.control.GerenciamentoVeiculos;
import com.mycompany.gestaooficina.control.GerenciamentoPecas;
import com.mycompany.gestaooficina.control.GerenciamentoServicos;
import com.mycompany.gestaooficina.control.GerenciamentoOrdemServico;
import javax.swing.JOptionPane;

/**
 *
 * @author silvestre
 */
public class Remover extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Remover.class.getName());

    /**
     * Creates new form Remover
     */
    public Remover() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVoltar = new javax.swing.JButton();
        jButtonRemoveFuncionario = new javax.swing.JButton();
        jButtonRemoveCliente = new javax.swing.JButton();
        jButtonRemoveVeiculo = new javax.swing.JButton();
        jButtonRemovePeca = new javax.swing.JButton();
        jButtonRemoveOS = new javax.swing.JButton();
        jButtonRemoveServico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonVoltar.setBackground(new java.awt.Color(255, 0, 0));
        jButtonVoltar.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(this::jButtonVoltarActionPerformed);

        jButtonRemoveFuncionario.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonRemoveFuncionario.setText("Remover Funcionario");
        jButtonRemoveFuncionario.addActionListener(this::jButtonRemoveFuncionarioActionPerformed);

        jButtonRemoveCliente.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonRemoveCliente.setText("Remover Cliente");
        jButtonRemoveCliente.addActionListener(this::jButtonRemoveClienteActionPerformed);

        jButtonRemoveVeiculo.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonRemoveVeiculo.setText("Remover Veiculo");
        jButtonRemoveVeiculo.addActionListener(this::jButtonRemoveVeiculoActionPerformed);

        jButtonRemovePeca.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonRemovePeca.setText("Remover Peça");
        jButtonRemovePeca.addActionListener(this::jButtonRemovePecaActionPerformed);

        jButtonRemoveOS.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonRemoveOS.setText("Remover Ordem de Serviço");
        jButtonRemoveOS.addActionListener(this::jButtonRemoveOSActionPerformed);

        jButtonRemoveServico.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButtonRemoveServico.setText("Remover Serviço");
        jButtonRemoveServico.addActionListener(this::jButtonRemoveServicoActionPerformed);

        jLabel1.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel1.setText("Remover");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonVoltar)
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 194, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRemovePeca, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonRemoveOS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRemoveCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRemoveFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRemoveVeiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                            .addComponent(jButtonRemoveServico, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(173, 173, 173))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonVoltar)
                        .addGap(25, 25, 25))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jButtonRemoveFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRemoveCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRemoveVeiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRemovePeca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRemoveServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRemoveOS)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        this.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonRemoveClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveClienteActionPerformed
        //REMOVER CLIENTE
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Digite o codigo do cliente a remover: "));
        GerenciamentoClientes genClient = GerenciamentoClientes.getInstance();
        if (genClient.buscarCliente(codigo) == null) {
            JOptionPane.showMessageDialog(null, "Cliente nao encontrado!");
        } else {
            genClient.removerCliente(codigo);
            JOptionPane.showMessageDialog(null, "Cliente (" + codigo + ") removido com sucesso!");
        }
    }//GEN-LAST:event_jButtonRemoveClienteActionPerformed

    private void jButtonRemovePecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemovePecaActionPerformed
        //REMOVER PECA
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Digite o codigo da peca a remover: "));
        GerenciamentoPecas genPeca = GerenciamentoPecas.getInstance();
        if (genPeca.buscarPeca(codigo) == null) {
            JOptionPane.showMessageDialog(null, "Peca nao encontrada!");
        } else {
            genPeca.removerPeca(codigo);
            JOptionPane.showMessageDialog(null, "Peca (" + codigo + ") removida com sucesso!");
        }
    }//GEN-LAST:event_jButtonRemovePecaActionPerformed

    private void jButtonRemoveOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveOSActionPerformed
        //REMOVER ORDEM DE SERVICO
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Digite o codigo da Ordem de Servico a remover: "));
        GerenciamentoOrdemServico genOS = GerenciamentoOrdemServico.getInstance();
        if (genOS.buscarOrdemServico(codigo) == null) {
            JOptionPane.showMessageDialog(null, "Ordem de Servico nao encontrada!");
        } else {
            genOS.removerOrdemServico(codigo);
            JOptionPane.showMessageDialog(null, "Ordem de Servico (" + codigo + ") removida com sucesso!");
        }
    }//GEN-LAST:event_jButtonRemoveOSActionPerformed

    private void jButtonRemoveServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveServicoActionPerformed
        //REMOVER SERVICO
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Digite o codigo do servico a remover: "));
        GerenciamentoServicos genServico = GerenciamentoServicos.getInstance();
        if (genServico.buscarServico(codigo) == null) {
            JOptionPane.showMessageDialog(null, "Servico nao encontrado!");
        } else {
            genServico.removerServico(codigo);
            JOptionPane.showMessageDialog(null, "Servico (" + codigo + ") removido com sucesso!");
        }
    }//GEN-LAST:event_jButtonRemoveServicoActionPerformed

    private void jButtonRemoveFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {
        //REMOVER FUNCIONARIO
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Digite o codigo do funcionario a remover: "));
        GerenciamentoFuncionarios genFunc = GerenciamentoFuncionarios.getInstance();
        if (genFunc.buscarFuncionario(codigo) == null) {
            JOptionPane.showMessageDialog(null, "Funcionario nao encontrado!");
        } else {
            genFunc.removerFuncionario(codigo);
            JOptionPane.showMessageDialog(null, "Funcionario (" + codigo + ") removido com sucesso!");
        }
    }

    private void jButtonRemoveVeiculoActionPerformed(java.awt.event.ActionEvent evt) {
        //REMOVER VEICULO
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Digite o codigo do veiculo a remover: "));
        GerenciamentoVeiculos genVeic = GerenciamentoVeiculos.getInstance();
        if (genVeic.buscarVeiculo(codigo) == null) {
            JOptionPane.showMessageDialog(null, "Veiculo nao encontrado!");
        } else {
            genVeic.removerVeiculo(codigo);
            JOptionPane.showMessageDialog(null, "Veiculo (" + codigo + ") removido com sucesso!");
        }
    }

        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Remover().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRemoveCliente;
    private javax.swing.JButton jButtonRemoveFuncionario;
    private javax.swing.JButton jButtonRemoveOS;
    private javax.swing.JButton jButtonRemovePeca;
    private javax.swing.JButton jButtonRemoveServico;
    private javax.swing.JButton jButtonRemoveVeiculo;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
